name: weather

services:
  weather:
    build:
      context: weather
      dockerfile: Dockerfile
    networks:
      - infra_network
    container_name: weather
    restart: always
    volumes:
      - .:/app
    ports:
      - "${WEATHER_PORT}:8000"
    env_file:
      - .env

networks:
  infra_network:
    external: true
