name: infra

services:
  postgres:
    image: postgres:17-alpine
    container_name: weather_postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tehran
    ports:
      - "${DB_PORT}:5432"
    networks:
      - weather_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  weather_network:
    name: weather_network
    external: true
